use_frameworks!

platform :ios, '9.0'

target 'AKYSqlite_swift_Example' do
  pod 'AKYSqlite_swift', :path => '../'

  target 'AKYSqlite_swift_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
